[build]
  cmd = "go build -o ./tmp/server.exe ./cmd/server"
  entrypoint = "./tmp/server.exe"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  exclude_file = [".env", ".env.local"]
  delay = 500

[log]
  time = false

[misc]
  clean_on_exit = true
